name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build With Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release
          files: target/release/hsr-overlay.exe
